### ISSUE TITLE
[ES] - Antenna 3 link no longer active

### ISSUE THREAD

**Issue by northernpowerhouse** [Free-TV/IPTV#102]
Hi There,

I can't resolve Antenna 3 with my setup, further inspection of the m3u provides this direct link: 
`http://4ce5e2d62ee2c10e43c709f9b87c44d5.streamhost.cc/m3u8/Spain/c96d4179790c2af.ts`

But that can't be resolved by my player (connecting from the UK) or by browser (connecting from Spain)

Is this down for anyone else?

**Comment by NezbednikSK** [comment]
Can confirm from Slovakia

**Comment by KAMI911** [comment]
Where is Antenna 3?
