### ISSUE TITLE
San Marino: RTV Sport updated stream

### ISSUE THREAD

**Issue by fparri** [Free-TV/IPTV#104]
The New stream for RTV Sport is https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/_definst_/smil:ch-02.smil/chunklist_b1692000_slita.m3u8

Sorry but I don't know how to open a pull request :(

**Comment by NezbednikSK** [comment]
Here you go.

**Comment by fparri** [comment]
> Here you go.

Thanks a lot :)
