### ISSUE TITLE
How to use the .py script?

### ISSUE THREAD

**Issue by HyperCheetah** [Free-TV/IPTV#108]

**Comment by NezbednikSK** [comment]
You run the python script, and it (re)generates playlist.m3u8. Then you point your IPTV player to the file.

**Comment by HyperCheetah** [comment]
> You run the python script, and it (re)generates playlist.m3u8. Then you point your IPTV player to the file.

How to run it?

**Comment by NezbednikSK** [comment]
Get the almighty [python](https://www.python.org/) installed, and open the command prompt.
The magic command is `python make_playlist.py`
