### ISSUE TITLE
Add channels from Pakistan & India

### ISSUE THREAD

**Issue by askfriends** [Free-TV/IPTV#112]
Add channels from Pakistan & India

**Comment by KAMI911** [comment]
Do you have working Channels for those?

**Comment by askfriends** [comment]
> Do you have working Channels for those?

by working channels u mean?
most of Pakistani and Indian channels stream their channel live thrugh yutube ig

**Comment by KAMI911** [comment]
Could you find working and FREE channels here?

https://github.com/Onemars/iptv-1/blob/master/channels/in.m3u
https://github.com/iptv-restream/iptv-channels/blob/master/channels/in.m3u
https://github.com/iptv-org/iptv/blob/master/streams/in.m3u

For example: 
#EXTINF:-1 tvg-id="JaihindTV.in" status="online",Jaihind TV (480p)
https://live.neestream.net/neestream_01/jaihindtv/index.m3u8?token=693400
This seems working but I do not know if it is FREE and we could use.

https://github.com/Onemars/iptv-1/blob/master/channels/pk.m3u
https://github.com/iptv-restream/iptv-channels/blob/master/channels/pk.m3u
https://github.com/iptv-org/iptv/blob/master/streams/pk.m3u

**Comment by KAMI911** [comment]
Did you find free channels?

**Comment by iamsajidjaved** [comment]
I need m3u8 for PTV Sports. The current one is not working.

At the moment I'm using IFRAME for **[ live cricket match streaming]**(https://sports.sajidjaved.com/) on **[PTV Sports](https://sports.sajidjaved.com/ptv-sports.html)**

**Comment by SoulReaper1996** [comment]
> I need m3u8 for PTV Sports. The current one is not working.
> 
> At the moment I'm using IFRAME for **[live cricket streaming](https://sports.sajidjaved.com/)** on [PTV Sports](https://sports.sajidjaved.com/ptv-sports.html)

hello Sajid Bhai. I would like a favor from you if possible. care to message me as soon as possible.?

**Comment by KAMI911** [comment]
Channel from India was added, I can not see working channels fro Pakistan. I am closing this issue. if you have channels to include please open a pull request.
