### ISSUE TITLE
[IT] mediaset channels not working anymore (legal reason?)

### ISSUE THREAD

**Issue by falket** [Free-TV/IPTV#116]
i tried to watch them from hypnotix linux mint tv player, i get these errors:

CHANNEL: 'Rete 4 Ⓢ Ⓖ' (https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(r4)/index.m3u8)
CHANNEL: 'Canale 5 Ⓢ Ⓖ' (https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(c5)/index.m3u8)
CHANNEL: 'Italia 1 Ⓢ Ⓖ' (https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(i1)/index.m3u8)
CHANNEL: 'Focus Ⓢ Ⓖ' (https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(fu)/index.m3u8)

Connessione a live3-mediaset-it.akamaized.net (live3-mediaset-it.akamaized.net)|80.67.66.186|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 451 Unavailable For Legal Reasons

It is possible to watch tv here, but i don't know how to extract an m3u or so... https://www.mediasetplay.mediaset.it/diretta/canale5_cC5

Thank you.

**Comment by Brenders** [comment]
Salve @falket hanno cambiato link, l'ho risolto un [mese fa](https://github.com/Free-TV/IPTV/pull/107/commits/3380703e251eb70d201190f9c86c959c9680fa46 ) ma bisogna aspettare che venga approvata la richiesta di pull, ti consiglio di rinominare il titolo con mediaset channel not worked, e ti consiglio rimuovere tutta la parte Connessione a e la risposta che ti invia perchè non bisogna creare allarmisti per un cambio di link e tipologia di file da richiedere.
Bisogna solo aspettare che vengano approvate le modifiche, ti chiedo di chiudere anche la issues dopo che hai modificato queste cose, grazie.

**Comment by Brenders** [comment]
@freetv332 @NezbednikSK you can close this issue because it was resolved with pull request #107
