### ISSUE TITLE
Canali Mediaset non trovati

### ISSUE THREAD

**Issue by 25fra** [Free-TV/IPTV#120]
Aggiungere canali Mediaset

**Comment by 25fra** [comment]
Come poter vedere i canali Mediaset

**Comment by Brenders** [comment]
Duplicate of #116
i canali gli ho già sistemati [da mesi](https://github.com/Free-TV/IPTV/pull/107/commits/3380703e251eb70d201190f9c86c959c9680fa46), il [pull](https://github.com/Free-TV/IPTV/pull/107) è in attesa di approvazione da parte di @freetv332 nella speranza che torni a revisionare tutti i pull request in attesa.

se vuoi puoi andare nel [mio repository](https://github.com/Brenders/IPTV) scaricare tutto ed eseguire il file `make_playlist.py` così da avere il file m3u aggiornato con tutte le modifiche in attesa di approvazione.

**Comment by Brenders** [comment]
@freetv332 @NezbednikSK you can close this issue because it was resolved with pull request #107
