### ISSUE TITLE
Automatic checkers, playlist update

### ISSUE THREAD

**Issue by KAMI911** [Free-TV/IPTV#142]
Hi Folks,

What do you think about to create automated CI workflow for updating playlist? I mean check the md file formats, check the created playlist before commit, and check the included links.

For example we could use:
* [Markdown linter](https://opensourcelibs.com/lib/markdown-lint)
* [M3U linter](https://www.npmjs.com/package/m3u-linter)
* Check links
* etc.

**Comment by NezbednikSK** [comment]
~~might have already done that one~~ I like the idea :D

**Comment by KAMI911** [comment]
Yes, I used it to find duplicates in #186.
I will integrate it as github action.

**Comment by KAMI911** [comment]
Added this:
https://github.com/Free-TV/IPTV/blob/automate/.github/workflows/test_playlist.yml
But it seems I haven't got right to test.

**Comment by freetv332** [comment]
Thanks @KAMI911, actions are a good idea, I'll have a look.

**Comment by KAMI911** [comment]
So We fire automatic playlist update up, and test channels is also working. Probably we need detailed report about non working channels. But this task is complete here.
