### ISSUE TITLE
Hungary - M1 News Channel no Longer Working

### ISSUE THREAD

**Issue by fjrider** [Free-TV/IPTV#145]
The "M1" news channel in the Hungary group is not working for the last few days.

Tried from a US IP address and also from a Hungary IP (through VPN).

**Comment by fjrider** [comment]
I found this stream (in website):
https://onlinestream.live/m1/videoplayer/5901-1

Don't know if there is a way to get an .m3u address for it?

**Comment by fjrider** [comment]
Or, this appears to be the public legal stream URL:

https://hirado.hu/elo/m1

How would we find out if it has an .m3u URL?

**Comment by NezbednikSK** [comment]
@fjrider think i can do that, will be back in a hour or so

**Comment by NezbednikSK** [comment]
well that was a bit faster, would this suffice?
https://sktv-forwarders.7m.pl/get.php?x=M1

**Comment by fjrider** [comment]
That one works, quality is a little low though.

Any idea what happened to the previous stream?

Is there a way to point the IPTV player straight to the legal HD stream on the website?

**Comment by NezbednikSK** [comment]
Yes, i'm aware. But that's the only quality the official site provides.
![2022-03-30_08-32](https://user-images.githubusercontent.com/47603275/160766356-cf63eca7-93bd-4241-8885-42c59d462798.png)
"legal HD stream on the website"
could you send me a link to it?

**Comment by fjrider** [comment]
https://onlinestream.live/m1/videoplayer/5901-1

**Comment by fjrider** [comment]
https://hirado.hu/elo/m1

**Comment by NezbednikSK** [comment]
that's max. 480p.

**Comment by fjrider** [comment]
Ok, better than nothing I guess :)

**Comment by NezbednikSK** [comment]
:)

**Comment by KAMI911** [comment]
I added these streams to the playlist.
