### ISSUE TITLE
Canada - seems nothing is working?

### ISSUE THREAD

**Issue by shulist** [Free-TV/IPTV#149]
Not sure what exactly is wrong but it seems that most (all?) of the streams I checked for Canada are not working.

For example the first channel on the Canada.md list is **CBC Toronto**. which links to `https://bozztv.com/teleyupp1/teleup-ydcl2V1MVC/playlist.m3u8` and it turns out this is a dead link as most of the others are also. 

I am using VLC 3.0.16 as my client and importing the Playlist.m3u8 directly.

...A little later on I have found that a few of the Canada channels seems to be working.  For instance Global News. Could it be that the providers for others have gone dark? 

Am I missing something here?

**Comment by NezbednikSK** [comment]
on it!

**Comment by NezbednikSK** [comment]
it seems that `bozztv.com` doesn't work
the first two channels seem to be on that

**Comment by KAMI911** [comment]
Probably they are geoblocked.
