### ISSUE TITLE
Food Network (Italy) stopped working

### ISSUE THREAD

**Issue by francescorosi27** [Free-TV/IPTV#158]
I think Discovery has pulled an epic prank on us by taking down the Food Network streaming link and saying that it "changed frequencies". While that did happen on the DTT, it obviously didn't happen in streaming, and I think this is Discovery being Discovery and making Food Network's streaming link only available on Discovery+. Here's a screenshot of what the channel looks like right now:
![Screenshot from 2022-04-21 21-08-17](https://user-images.githubusercontent.com/52544979/164535640-6776e528-fed7-45a2-89dd-6ff6eb70510c.png)
The text translates to:
"Food Network has changed frequencies. To continue watching it, retune your television from your remote's menu. (?)"
This is probably never going to be fixed, since you simply cannot extract an HLS stream from Discovery+ easily. You would have to make an API for that. And while the "WorldLiveTV" team have already done that for K2 and Frisbee, they haven't done it yet for Food Network. Anyways, that's it. Just wanted to let everyone know about this.

**Comment by NezbednikSK** [comment]
yeah. seems like it.

**Comment by Brenders** [comment]
now the link of channel is down because site responsed with Invalid URL, next commit I remove channel from list.

**Comment by infid0** [comment]
Sure @Brenders . But unluckily the problem not is for _Food Network_ only. The problem is for every **Discovery Italy** channels: Nove, RealTime, Dmax, etcetera... :/
