### ISSUE TITLE
Problems with popular news channels

### ISSUE THREAD

**Issue by KiraSol** [Free-TV/IPTV#169]
Hello! Thank you very much for your playlist! We have problems with two news channels that I like to watch:

1) France 24 English doesn't work at all. It happened about a week ago.

2) BBC World News constantly freezes, it's very unstable. Yes, I live far away from United Kingdom but any other channels work perfectly.

**Comment by KiraSol** [comment]
Is anybody maintaining this IPTV list now? The problems still exist. Stream of France 24 English doesn't work at all. Stream of BBC World News has freezed with one still frame. May I help you somehow to fix these bugs?

**Comment by NezbednikSK** [comment]
or a HLS stream if you like those more... http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/FRANCE24English/live

**Comment by KiraSol** [comment]
Perfect! Could you please add it to this Free-TV playlist in place of non-working stream?

**Comment by KiraSol** [comment]
Perfect! Would you kindly add it to this Free-TV playlist in place of non-working stream?

**Comment by KiraSol** [comment]
Thank you very much! And we also need to do something with freezed BBC World News stream in this playlist.

**Comment by NezbednikSK** [comment]
Can't.
> BBC World News is an international English-language pay television network

**Comment by KiraSol** [comment]
It's sad. OK. May I ask when will playlist.m3u8 file be rebuild?

**Comment by NezbednikSK** [comment]
Who knows? :)

**Comment by KAMI911** [comment]
Could we close this?

**Comment by KiraSol** [comment]
Yes, I think so. France 24 English works. NezbednikSK said there is nothing you can do with BBC World News.
