### ISSUE TITLE
Canada: changed URL for ICI RDI and ICI Télé HD

### ISSUE THREAD

**Issue by ermtl** [Free-TV/IPTV#177]
In canada.md, 2 french language channels changed their URL.

I created a pull request for it.

ICI RDI 
----------
Old : https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master_2500.m3u8
New : https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master.m3u8

ICI Télé HD 
---------------
Old : https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master_2500.m3u8
New : https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master.m3u8

**Comment by KAMI911** [comment]
Pull request merged! Thank you!
