### ISSUE TITLE
Spain - La Sexta not working

### ISSUE THREAD

**Issue by Tizioincognit0** [Free-TV/IPTV#179]
The "La Sexta" channel in the Spain group is not working.

**Comment by freetv332** [comment]
Everyone can participate or look for streaming URLs.

Whether it's to remove channels or to add new ones, please provide Pull Requests directly rather than issues.

**Comment by NezbednikSK** [comment]
i don't wanna reopen this but it seems the channel is behind a paywall now(?)

**Comment by Tizioincognit0** [comment]
> i don't wanna reopen this but it seems the channel is behind a paywall now(?)

I confirm this.
