### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by vdej8** [Free-TV/IPTV#183]

**Comment by NezbednikSK** [comment]
![2022-08-11-070852_3840x1080_scrot](https://user-images.githubusercontent.com/47603275/184068147-8867af82-b94c-4e68-b068-ba2073194d5d.png)
I'm in there too, it's some canadian company complaining about their links being here... maybe they should be removed?

**Comment by KAMI911** [comment]
Thank you for bring our attention to this:
Affected file is:
https://github.com/Free-TV/IPTV/blob/3f64a66613051f67f6d5fc4892dc758475855eb0/playlist.m3u8
lines:
Lines: 145, 147, 149, 151, 153, 155, 157, 159, 161, 165

**Comment by cool2apps** [comment]
Is it legal to use these stream links inside a Google Play Store or App Store app?
