### ISSUE TITLE
Missing italian EPG ID

### ISSUE THREAD

**Issue by infid0** [Free-TV/IPTV#207]
@KAMI911 or @NezbednikSK please, you can test these missing italian epg id for me? Unluckily i can't, thank you so much guys! :3 

01) Rai 1 Ⓖ > Rai1.it
02) Rai 2 Ⓖ > Rai2.it
03) Rai 4 Ⓖ > Rai3.it
20) Canale 20 Ⓖ > 20Mediaset.it
21) Rai 4 Ⓖ > Rai4.it
23) Rai 5 Ⓖ > Rai5.it
24) Rai Movie Ⓖ > RaiMovie.it
25) Rai Premium Ⓖ > RaiPremium.it
42) Rai Gulp Ⓖ > RaiGulp.it
48) Rai News 24 Ⓖ > RaiNews24.it
54) Rai Storia Ⓖ > RaiStoria.it
57) Rai Scuola Ⓖ > RaiScuola.it

**Comment by Brenders** [comment]
@infid0 where did you get these epg from? so I start to update all the epg of the channels

**Comment by infid0** [comment]
@Brenders i've found the epg id of old channels in an old playlist no more working, mediaset 20 on internet. Anyway, please test if these id works before to put into the playlist. Thank you!

**Comment by Brenders** [comment]
> @Brenders i've found the epg id of old channels in an old playlist no more working, mediaset 20 on internet. Anyway, please test if these id works before to put into the playlist. Thank you!
 
i have find this EPG
https://iptv-org.github.io/epg/guides/it/raiplay.it.epg.xml.gz

**Comment by infid0** [comment]
OK, thank you @Brenders for testing the epg id!
