### ISSUE TITLE
Problem with Russian channels

### ISSUE THREAD

**Issue by Miami77** [Free-TV/IPTV#217]
The other countries are all working fine, but on the Russian section only 1 or 2 are functional.

**Comment by NezbednikSK** [comment]
any urls?

**Comment by Miami77** [comment]
> any urls?

What do you mean? The ones that don't work or do you need working urls to replace the ones that do not work anymore?

**Comment by NezbednikSK** [comment]
the ones that should replace the non-working

**Comment by Miami77** [comment]
> the ones that should replace the non-working

I can not give you working urls for every channel, but for some I found ones...

Channel one - https://edge1.1internet.tv/dash-live2/streams/1tv-dvr/1tvdash.mpd

Russia24 - http://cdnmg.secure.live.rtr-vesti.ru/hls/russia_24/playlist_3.m3u8

RTR russia - http://cdnmg.secure.live.rtr-vesti.ru/live/smil:rtrp.smil/chunklist_b1600000.m3u8

Russia 1 - http://cdnmg.secure.live.rtr-vesti.ru/live/smil:rhd.smil/chunklist_b1200000.m3u8

Рен ТВ - http://ad-hls-rentv.cdnvideo.ru/ren/smil:ren.smil/chunklist_b1024000.m3u8

Мир - http://hls.mirtv.cdnvideo.ru/mirtv-parampublish/mirtv_2500/playlist.m3u8

**Comment by Brenders** [comment]
I think this issues is a duplicate of #182 and #134

**Comment by Brenders** [comment]
> It's not because they actually gave links to working streams instead of just complaining @Brenders

yes, you're right the links work I had a problem with the multimedia player, do I create a pull request?

**Comment by Miami77** [comment]
Thanks for your help, most of them work again! ;)
