### ISSUE TITLE
Euronews English broken URL

### ISSUE THREAD

**Issue by KiraSol** [Free-TV/IPTV#230]
Hello! **Euronews Live Ⓨ** channel from group **News (EN)** doesn't work because broadcaster changed YouTube-stream a month ago. Please change URL to [https://www.youtube.com/watch?v=ntmPIzlkcJk](https://www.youtube.com/watch?v=ntmPIzlkcJk) and update the Free-TV playlist! Many thanks for your work!

**Comment by KAMI911** [comment]
I tried directly and via fullspeed but it does not start...

**Comment by infid0** [comment]
I'm sorry for the intrusion, but i've changed the YT url with a static url: 
https://euronews.alteox.app/hls/en_stream.m3u8
Works fine (with me) and it don't change every X days like YT.

**Comment by KAMI911** [comment]
@infid0, thanks for the patch. Fixed.
