### ISSUE TITLE
pls add iran channel (: 

### ISSUE THREAD

**Issue by Kinggmahdi** [Free-TV/IPTV#239]
pls add iran channel (;

**Comment by KAMI911** [comment]
@Kinggmahdi , do you know free channels, free streams from there? I found these: https://iptv-org.github.io/?q=iran

**Comment by infid0** [comment]
Hi, i've started the Iran playlist here: 
https://github.com/Free-TV/IPTV/blob/master/lists/iran.md
But in Iran the 99% of channels is broacasted by "Sepehr" and this provider use url with tokens who changes every X hours. :/

**Comment by infid0** [comment]
> hook me up with the stream link and i'll figure it out

https://sepehr.irib.ir/live

**Comment by infid0** [comment]
Is a third party stream example: 
https://telewebion.com/live/tv3
http://www.imvbox.tv/it/iribtv3/live-channel/play
etcetera...
But i don't know our politic about third party stream, for this reason i've put original url marked like not working.

**Comment by infid0** [comment]
LOL honestly i can't understand why all this job, these channel are a public tv visible from everybody :/

**Comment by Ismail-BooM** [comment]
THX

**Comment by Ismail-BooM** [comment]
how do i solve this problem ![20221119_205103.jpg](https://user-images.githubusercontent.com/114135277/202868915-46fcfc55-abc9-498e-8c72-cca0f7c16c97.jpg)

**Comment by KAMI911** [comment]
> Is a third party stream example: https://telewebion.com/live/tv3 http://www.imvbox.tv/it/iribtv3/live-channel/play etcetera... But i don't know our politic about third party stream, for this reason i've put original url marked like not working.

Regarding to out [philosophy](https://github.com/Free-TV/IPTV#philosophy) we could use free streams of free channels from other sources too. Are they free to view in Iran?

**Comment by infid0** [comment]
Yes @KAMI911 is the public television of Iran, the original streaming of channels are available here: 
https://sepehr.irib.ir/live
They are visible from all and not geoblocked, the problem are the url with dynamic tokens... But if i've the "OK" i'm ready to put the 3rd party streams asap. :3
