### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by teranus** [Free-TV/IPTV#243]
First to say that this list is amazing.
If there would be an epg available for the complete list, it would be even more amazing

**Comment by KAMI911** [comment]
If you want to contribute, you can send pull requests (PR). Simply add links from here: https://iptv-org.github.io/
TVG-ID is EPG info, and also you could link the picture too.

**Comment by KAMI911** [comment]
Format is like this:
https://github.com/Free-TV/IPTV/edit/master/lists/argentina.md

**Comment by telluroid** [comment]
Why do the TVG-IDs differ between https://epg.best/available-channels and https://iptv-org.github.io/ ?
I guess I should use the latter?

**Comment by KAMI911** [comment]
@teranus: You could open Pull Request from your repo if you want to contribute with more EPG codes. Thank you in advance!

**Comment by Brenders** [comment]
> If you want to contribute, you can send pull requests (PR). Simply add links from here: https://iptv-org.github.io/ TVG-ID is EPG info, and also you could link the picture too.

Thanks, I just opened a PR request and posted these epgs.

**Comment by KAMI911** [comment]
Thank you for all contributions.
