### ISSUE TITLE
All Italian RAI channels do not work

### ISSUE THREAD

**Issue by pigeonskiller** [Free-TV/IPTV#269]
As in title, all Italian RAI channels do not work anymore.
Please solve.
Thanks and have a nice day.

**Comment by infid0** [comment]
Hi, i've tested the Rai channels on Linux Mint with Hypnotix, Windows with Kodi, Android with Fennec, Samsung TV with M3U IPTV and the channels works fine. :|

**Comment by KAMI911** [comment]
Probably are they geofenced? 
![kép](https://user-images.githubusercontent.com/5292264/211400192-54b4367e-ebbc-4e37-95a6-650b924b2666.png)

**Comment by infid0** [comment]
I don't know why, but the Rai streaming link don't works with VLC. Maybe he is italian and without vpn, but use the playlist with VLC... :/

**Comment by infid0** [comment]
> because they are not direct links, the links redirect to the video stream.
Ok, anyway i read that this problem it was fixed on the nightlies version. Finally!  :3
