### ISSUE TITLE
Add regional Dutch channels 

### ISSUE THREAD

**Issue by pvdl** [Free-TV/IPTV#28]
Please add also the Dutch regional channels in the Netherlands.
Most streams are in HD, some in SD.
I don't know if the streams are geo-restricted, but the streams are tested and working well.

Regional channels in the Netherlands:
https://nl.wikipedia.org/wiki/Regionale_omroep#Nederland

Omrop Fryslân
https://d3pvma9xb2775h.cloudfront.net/live/omropfryslan/stream04/index.m3u8

RTV Noord
https://media.rtvnoord.nl/live/rtvnoord/tv/3e8fe3c1-0868-49b0-b2f3-7dd6eb30651f/index.m3u8

RTV Drenthe
https://cdn.rtvdrenthe.nl/live/rtvdrenthe/tv/1080p/prog_index.m3u8

RTV Oost
https://mediacdn.rtvoost.nl/live/rtvoost/tv-oost/index.m3u8

Omroep Gelderland
http://web.omroepgelderland.nl/live/livetv.m3u8

RTV Utrecht
http://media.rtvutrecht.nl/live/rtvutrecht/rtvutrecht/index.m3u8

Omroep Flevoland
https://d5ms27yy6exnf.cloudfront.net/live/omroepflevoland/tv/index.m3u8

NH Nieuws
Stream is protected.
Protected stream can be found here: https://www.nhnieuws.nl/media

RTV Rijnmond
http://d3r4bk4fg0k2xi.cloudfront.net/rijnmondTv/index.m3u8

Omroep West
http://d2dslh4sd7yvc1.cloudfront.net/live/omroepwest/ngrp:tv-feed_all/playlist.m3u8

Omroep Zeeland
http://d3isaxd2t6q8zm.cloudfront.net/live/omroepzeeland/tv/index.m3u8

Omroep Brabant
http://d3slqp9xhts6qb.cloudfront.net/live/omroepbrabant/tv/index.m3u8

L1
http://d34pj260kw1xmk.cloudfront.net/live/l1/tv/index.m3u8

**Comment by freetv332** [comment]
Please make a pull request.

**Comment by freetv332** [comment]
If the regional channels show the same content, please only include one.

**Comment by pvdl** [comment]
Pull request #31
