### ISSUE TITLE
KBS 2 isn't working anymore

### ISSUE THREAD

**Issue by christiangriffin** [Free-TV/IPTV#281]
KBS 2 (South Korea) isn't working. When i try to watch it, the channel displays a copyright relatef error, and it's strange since the other KBS channels (KBS 1, KBS Life, KBS Drama and KBS Story) are working without any probelms. Hope you can resolve this problem. Have a good day!

**Comment by infid0** [comment]
Hello and thanks for the report. I've tested "KBS 2TV" just now and works fine for me. Maybe it was only a tv program without permission of transmission by internet... It's not unusual. :3

**Comment by KAMI911** [comment]
Please reopen, if this is still an issue.
