### ISSUE TITLE
Freezes Kodi

### ISSUE THREAD

**Issue by YesTrustMe** [Free-TV/IPTV#293]
When accessing most channels.

**Comment by infid0** [comment]
Hi, if you report some channel we can to investigate why happens that, but remember: first of all this playlist is the database of [Linux Mint Hypnotix](https://github.com/linuxmint/hypnotix) app. Thank you! :3

**Comment by KAMI911** [comment]
If our list problematic in Kodi, we should take care:
a) to make compatible
b) if not possible report to Kodi's developers

**Comment by KAMI911** [comment]
Could you check again? I found errors in playlist file. Also https://iptv-org.github.io/epg/guides/* EPG links are not available at the moment or anymore - that also could be a problem. Probably we need other EPG source.
