### ISSUE TITLE
Switzerland RSI La1/La2 - HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by drego85** [Free-TV/IPTV#300]
Hi,
I wanted to report that for the past several days it has not been possible to watch Switzerland TV RSI La1 and La2.

The two m3u8 files return HTTP error 403.

```
curl http://190.2.155.162/RSI1/index.m3u8 -I
HTTP/1.1 403 Forbidden
Connection: keep-alive
Date: Wed, 01 Mar 2023 15:25:21 GMT
Content-Length: 1147
Server: Streamer 23.02
X-Route-Time: 149
X-Run-Time: 175
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, DELETE, OPTIONS
Access-Control-Expose-Headers: Server, range, X-Run-Time, X-Sid, Content-Length, Location
Access-Control-Allow-Headers: x-vsaas-session, x-no-redirect, origin, authorization, accept, range, content-type, x-add-effective, session, x-originator, x-sid
X-Deny-Reason: backend_denied
```

**Comment by infid0** [comment]
Hi if you are italian and living in Italy is normal, because La1/2 are geo blocked and not visible out of Switzerland. The only way is to use a vpn and to have a Switzerland ip. :3

**Comment by drego85** [comment]
@Brenders, may I ask you for your support. 

You had added these two channels, maybe you remember some details about the source and related server.

Thanks

**Comment by infid0** [comment]
> I always thought that the server (190.2.155.162) is not officially from Swiss TV, but of someone who was offering us a "proxy" server!

Ok now has a sense. I'm apologize for the superficial answer, but i never checked the swiss page and i thought they were official url from the site. Sorry. :/
Thank you for the report, if @Brenders can't help us i will put the official stream, thank you again! :3

**Comment by infid0** [comment]
Well or third party stream, or nothing... Ok... :|
