### ISSUE TITLE
Add Polish channels, maybe?

### ISSUE THREAD

**Issue by NezbednikSK** [Free-TV/IPTV#304]
I found myself watching TVP World and I wondered if anyone would be interested in adding https://stream.tvp.pl/ (the channels use a simple API to retrieve the stream link, nothing extreme (and no DRM!))

**Comment by infid0** [comment]
Ok thanks @NezbednikSK i'll make a Poland page in these days! :3

**Comment by aprof28** [comment]
Can I ask for an update of Polish programs?
