### ISSUE TITLE
Pluto TV channels are not currently working

### ISSUE THREAD

**Issue by ADHDefy** [Free-TV/IPTV#333]
I'm using [Open-TV](https://github.com/Fredolx/open-tv) as a client on Linux (Fedora). Most channels seem to work well (with some random exceptions, like Nick, TV Tokyo, Cartoonito, etc.) but none of the Pluto channels will open.

**Comment by ADHDefy** [comment]
> Which country are they in?

Sorry for the long delay. I believe they're US-based? I am also in the US, so it shouldn't be a region block or anything.

**Comment by stl3** [comment]
Possibly cors related issue. I don't know how you'd allow that in a client like open-tv but that's just my guess as I ran into a similar issue and solved it on my browsers by allowing cors (cross origin resource sharing). If there's some kind of console log in open-tv it would probably show something like that. Just a possibility anyways.

**Comment by KAMI911** [comment]
Merged a fix, reopen if the problem still exist.
