### ISSUE TITLE
Streams from s13.tntendirect.com are not working anymore

### ISSUE THREAD

**Issue by locness3** [Free-TV/IPTV#343]
Many channels from France here (eg France 2 or TF1) use a URL from the website s13.tntendirect.com, however it seems these are now broken. Can't open them from a media player, in a web browser it just says "Forbidden"

**Comment by KAMI911** [comment]
Is it still an issue?

**Comment by locness3** [comment]
Looks like those channels have feeds that work now, so no longer an issue for now. Thanks!
