### ISSUE TITLE
BBC channels not working

### ISSUE THREAD

**Issue by misanthroope** [Free-TV/IPTV#467]

**Comment by dp247** [comment]
Which ones?

**Comment by thetommyho** [comment]
all the one with the timeout tag, thanks!
![bbc](https://github.com/Free-TV/IPTV/assets/65223363/a8c58a5f-e46b-48cf-b97a-223d2aa7af97)

**Comment by dp247** [comment]
Are you located within the UK?

**Comment by dp247** [comment]
That'll be the reason - those streams are the ones used by iPlayer. I know of some alternates though that I can merge in

**Comment by misanthroope** [comment]
That would be great
Cheers :)
