### ISSUE TITLE
Italy Tv on the Free TV-App

### ISSUE THREAD

**Issue by Salva-C** [Free-TV/IPTV#510]
Where can I get links to watch Rai 1, Rai 2, Rai 3, Rete 4, Chanale 5, Italia1, Italia2 etc. on the app?

**Comment by Brenders** [comment]
for all nations use this one `https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8` or for Italy use this one `https://github.com/Free-TV/IPTV/raw/master/playlists/playlist_italy.m3u8` and this one `https://github.com/Free-TV/IPTV/raw/master/playlists/playlist_zz_vod_it.m3u8`

@infid0 issues has been solved. Close this.
