### ISSUE TITLE
Almost no French Channel are working.

### ISSUE THREAD

**Issue by garelp** [Free-TV/IPTV#521]
Most of the them are using live.ktv.zone which appears to be dead..

How to fix this?

thanks

**Comment by rickeymandraque** [comment]
> Most of the them are using live.ktv.zone which appears to be dead..
> 
> How to fix this?
> 
> thanks

Hello,
It's not possible.
knet had security vulnerabilities which have been closed.
https://github.com/iptv-org/iptv/issues/15859

**Comment by Brenders** [comment]
@infid0 Check if you need to close this issue because apparently it was resolved with pull request https://github.com/iptv-org/iptv/pull/15873
