### ISSUE TITLE
sktv-forwarders.7m.pl is dead (Slovak and Czech channels)

### ISSUE THREAD

**Issue by santomet** [Free-TV/IPTV#571]
sktv-forwarders, through which state Slovak (RTVS/STVR) and Czech (ČT) TV Channels are routed is dead.
I have contacted the original author (@NezbednikSK ) who said that the hosting has cancelled his account without any notice and with that, the source code has gone. Also, he is not going to work on the project anymore.

Of course, the only reason for the forwarder is to get an unique link to a working playlist.
I have an ambition to recreate the project mainly because my own [code](https://github.com/santomet/santomet-playground/blob/master/rtvs2vlc/rtvs2vlc.php) originally intended for getting around geoblocking is still working for RTVS and can be used straight away. I also got hints from NezbednikSK about how he worked with ČT streams.

One question for the experienced guys around here: Do you know about a well-suited PHP hosting for this purpose? Even though in my opinion this is completely legal, I don't want to risk using hosting where my other projects are.

Maybe a bonus question: by any chance, does anyone have backed-up source code for sktv-forwareds? (it was possible to show it via a link on the webpage but that did not get it to archive.org sadly)

**Comment by fraudiay79** [comment]
I have one that I backed up back in January.  Hope it helps:

https://github.com/fraudiay79/logos/blob/master/sktv-forwarders-source-JwH3kD.zip

**Comment by fraudiay79** [comment]
[sktv-forwarders-source-JwH3kD.zip](https://github.com/user-attachments/files/16112534/sktv-forwarders-source-JwH3kD.zip)

**Comment by VlastikYoutubeKo** [comment]
@fraudiay79 used the source, it's hosted on [my serv00 website](https://menticek.serv00.net/iptv)

I will probably tommorow replace the links with the new thingy

**Comment by fraudiay79** [comment]
Can you add TVM Malta using this?

**Comment by VlastikYoutubeKo** [comment]
> Can you add TVM Malta using this?

No
because I have no idea where to get the stream from, and how to code it 😛

**Comment by santomet** [comment]
Very well, I am satisfied. I have also created mirror of the code [here](https://github.com/santomet/sktv-forwarders). 

I intend to maintain it, at least the Czech and Slovak part

**Comment by NexusSfan** [comment]
> Very well, I am satisfied. I have also created mirror of the code [here](https://github.com/santomet/sktv-forwarders).
> 
> I intend to maintain it, at least the Czech and Slovak part

I didn't expect you to fork my repo! Thanks for contributing, I watch Czech shows on IPTV.
