### ISSUE TITLE
Forwarders

### ISSUE THREAD

**Issue by NezbednikSK** [Free-TV/IPTV#60]
I have a PHP script that sends request to a particular address, extracts the stream URL (that is dynamic) and forwards to it.
If i host it online, can I submit it here or is it not allowed?

Concrete example: [live-source.js](https://embed.livebox.cz/ta3_v2/live-source.js) contains the stream URL.
The PHP script sends the request, extracts the URL and forwards to it.

**Comment by NezbednikSK** [comment]
Update: in Australia, i found urls from c.mjh.nz, so they probably are allowed.
![image](https://user-images.githubusercontent.com/47603275/125397855-d0b0e280-e3ae-11eb-842a-72c9554282dc.png)

**Comment by freetv332** [comment]
If it helps adding channels we couldn't have otherwise, then yes.

**Comment by NezbednikSK** [comment]
Well that's great! I've already made a script to add the three major channels here in Slovakia, :-)
Is [RunKit](https://runkit.com/home) fine for the forwarders by the way? It works fine for me, although a bit slow.

**Comment by guillerber** [comment]
can you install the script on a server?

**Comment by NezbednikSK** [comment]
yes, i have it running locally @guillerber
