### ISSUE TITLE
Japan channels need updates

### ISSUE THREAD

**Issue by Bonita1115** [Free-TV/IPTV#613]
Could you please japan TV channel updates? Most of NHK channel is messed up and same channel and other channels unwatchable. Seems they changed channel address or something. Thank you

**Comment by jirocho999** [comment]
昨日から全く視聴出来なくなりました。
アップデートをお願いします。

**Comment by AdalbertKhoolsaat** [comment]
Experiencing similar issues with most of the Japanese tv playlist since yesterday.
An update would be greatly appreciated.

**Comment by imtaku** [comment]
I'm not sure, but it seems that it's still not fixed. I still can't watch content on the Japanese channels. An update would be greatly appreciated, Thanks.

**Comment by oobayashi** [comment]
playlist_japan.m3u8をローカルにダウンロードしてVLC media playerで開いて、日本のチャンネルを視聴していたのですが、２，３日前から見れなくなりました。YoutubeやXでも話題にあがっています。aldrinzigmundvさんが、壊れたjp-primehomeリンクを修正と書かれていますが、あいかわらず、日本のチャンネルのほとんどが見れません。私の方で何かすることがあるのでしょうか？japan.mdファイルというのは使ったこともありません。技術的なことは詳しくないので、私は何もしなくても、日本のチャンネルを今まで通り見ることができるのでしょうか？それとも、何か私の方でやらなければいけないのでしょうか？教えて下さい。

**Comment by aldrinzigmundv** [comment]
The `playlist_japan.m3u8` file will automatically update once my pull request for the `japan.md` file (#614) is merged. However, it hasn’t been merged yet. In the meantime, you can manually update your copy of `playlist_japan.m3u8` by adding `&isp=7` to all links associated with **jp-primehome**, or changing the value to `7` if the link already has `isp=n`, similar to what I did in my commit.

If you're unable to make these changes yourself, I’d be happy to assist. Just reach out to me at support@aldrinzigmund.com, and I’ll send you a modified version via email. Alternatively, you can check my app [Digilog TV - 日本版](https://github.com/aldrinzigmundv/digilogtvjp), which has the same links already updated and is available for Android and Google TV—whichever works best for you.

**Comment by oobayashi** [comment]
私は技術者ではないので、自動的に更新されるのを待つだけです。いつ自動的に更新されるのでしょうか?

**Comment by Bonita1115** [comment]
@aldrinzigmundv I really appreciate your hard working. To peoole live in other counrty really need those channels. I fixed it and Thank you very much!

**Comment by aldrinzigmundv** [comment]
@Bonita1115 No problem at all. Always happy to help.

**Comment by Bonita1115** [comment]
> @Bonita1115 No problem at all. Always happy to help.

I am so sorry to bothering you, it happend again. All channels can't watch in Japanese Channels again. 
Please update codes if you have a chance.
I really appreciate your support.

**Comment by aldrinzigmundv** [comment]
@Bonita1115 There may already be a solution after another update from jp-primehome. I have time tomorrow morning to do some testing and will immediately submit a pull request once I confirm the new links are working. Hopefully, we won’t encounter the worst-case scenario where the links become tokenized...

**Comment by X1288664** [comment]
@aldrinzigmundv 
Where I can updated .m3u8 files?
Plz link _(._.)_
