### ISSUE TITLE
Legality of the logos

### ISSUE THREAD

**Issue by NezbednikSK** [Free-TV/IPTV#65]
Hey, I've been wondering: the streams are legal, yes, but what about the logos? Wouldn't it be better to link the logos from their official website and not to upload it from imgur? I am wondering if this is legal, actually. To submit all the logos, y'know.

**Comment by infid0** [comment]
It's a good question. Maybe a generic disclaimer like: _“all third party logos and trademarks are the property of their respective owners”_ would be suffice, i don't know.

**Comment by NezbednikSK** [comment]
In my opinion, linking them right from the website would be better. As they provide a live broadcast, there is 99% chance their logo is sticked somewhere on the page.

**Comment by freetv332** [comment]
If somebody has an issue with one of the logos they can simply ask for its removal or PR a change.

Pointing to a website is a really bad idea because it can lead to 404, 500, DNS errors, etc.. imgur hosts indefinitely and we can modify any logo if need be.
