### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by khalil403** [Free-TV/IPTV#67]
hi hope you are well
every channel i click on  says forbidden?

**Comment by NezbednikSK** [comment]
Can you specify what channels?

**Comment by khalil403** [comment]
hi thank you for the reply and sorry i should of been more specific. i go on the uk folder and any channels eg bbc1 bbc2 e4 when i click on the link it goes to a page and says forbidden, Thanks !

**Comment by NezbednikSK** [comment]
Yeah, they don't work. #48

**Comment by khalil403** [comment]
thanks!
