### ISSUE TITLE
tvg-id

### ISSUE THREAD

**Issue by NezbednikSK** [Free-TV/IPTV#69]
Uhh, so I would like your opinion.
I added Markíza, Doma and Dajto.
They only provide an SD stream for free and want you to pay for the HD stream.
Technically, this is not illegal as it is streamed off their servers.
Should the channels be removed / kept in SD?

**Comment by freetv332** [comment]
Can you access the HD streams without paying?

**Comment by NezbednikSK** [comment]
Yep

**Comment by NezbednikSK** [comment]
The URLs are formatted the same as for some other channels, so with editing the URLs you can access them without paying.
Normally, you can only access the SD one for free. IMO we should remove them, as they are region-locked and the channel is officially pay-tv but their site offers a SD stream.

Let me make a PR that removes them.

**Comment by NezbednikSK** [comment]
+ Would you mind me rewriting the RTVS forwarder in PHP? RunKit is just so slow, ;-)

**Comment by NezbednikSK** [comment]
Also what about IDs for channels? tvg-id, I mean

**Comment by freetv332** [comment]
you mean channel numbers?

**Comment by nezbednik** [comment]
Nope, i meant IDs. They are used to show the correct EPG. Might be a good idea to implement them somehow, as (G), (S) and (Y) break them when not specified.

**Comment by NezbednikSK** [comment]
Oh yeah it is me, my alt account,

**Comment by freetv332** [comment]
It sounds like a good idea, but where do you find these IDs?

**Comment by NezbednikSK** [comment]
https://github.com/iptv-org/epg/blob/master/codes.csv

**Comment by freetv332** [comment]
OK let's add them. You can start modifying the lists, I'll adapt the program to include them in the playlist.

**Comment by NezbednikSK** [comment]
Could you try making the script check if the ID is specified? Y'know, adding IDs to 700+ channels is quite the task.

**Comment by amyleeman** [comment]
> https://github.com/iptv-org/epg/blob/master/codes.csv

404, you must use this url now: https://iptv-org.github.io/epg/index.html

**Comment by amyleeman** [comment]
> Could you try making the script check if the ID is specified? Y'know, adding IDs to 700+ channels is quite the task.

Script for format like in this pull request https://github.com/Free-TV/IPTV/pull/96
```
#!/usr/bin/env python3
import os
import re
for filename in sorted(os.listdir(".")):
    if filename == "README.md" or not filename.endswith(".md"):
        continue
    with open(filename, encoding='utf-8') as markup_file:
        group = filename.replace(".md", "").title()
        for line in markup_file:
            if "<h1>" in line.lower() and "</h1>" in line.lower():
                group = re.sub('<[^<>]+>', '', line.strip())
            if not "[>]" in line:
                continue
            split = line.split("|")
            try:
                epg_line = split[5].strip()
            except:
                epg_line = ''
            if not epg_line:
                print("EPG not found in file '{}' for channel '{}'".format(filename, split[2].strip()))
```

**Comment by KAMI911** [comment]
Could we add EPG support? AFAIK we have to add an another field to md files. I can manage to add that field if it is in the channel line and change the python code too.
Should I create a separated epg branch for testing and implementing, or an cloned repo? Could someone add EPG ids to *.md files?
Thanks!

**Comment by NezbednikSK** [comment]
I'm up!

**Comment by KAMI911** [comment]
I started to add EPG id / tvg-id here:
https://github.com/Free-TV/IPTV/tree/epg
Playlist is here:
https://raw.githubusercontent.com/Free-TV/IPTV/epg/playlist.m3u8
Should I add something more like links to EPG XML files somehow, or this is enough to start use the tvg-id? The updated python script can work with and without EPG id.
I added tvg-id to few Hungarian channels. What is your opinion? What is the next task? If this provides a good solution and we got a few lists with tvg-id I can merge it to the master.

**Comment by NezbednikSK** [comment]
sounds good! i guess it's a matter of adding IDs for every channel now :)

**Comment by NezbednikSK** [comment]
and since they're IDs, https://github.com/iptv-org/epg could be used alongside the playlist to show the EPG itself

**Comment by KAMI911** [comment]
@NezbednikSK: I updated the Hungarian file, could you add more for testing?

**Comment by KAMI911** [comment]
Added x-tvg-url support.
@NezbednikSK

**Comment by NezbednikSK** [comment]
Sure!

**Comment by NezbednikSK** [comment]
#184

**Comment by KAMI911** [comment]
Thank you!

**Comment by KAMI911** [comment]
It seems it is working with external EPG. Could you add more channels tvg-ids?

**Comment by KAMI911** [comment]
Added 3a220e1a8db7d55f886649c02dafb9d9b84a0eb7
@NezbednikSK , @freetv332 , @riqueenz 
Could you contribute additional EPG ids?
I used https://iptv-org.github.io/ page and the search on this page.
It would be nice to finish this ASAP then merge into the master branch. What are your opinions?

**Comment by NezbednikSK** [comment]
on it

**Comment by KAMI911** [comment]
Do you mind if I close this issue? Since the main task has solved to have EPG id support.
