### ISSUE TITLE
Regarding Indian channels

### ISSUE THREAD

**Issue by rht125** [Free-TV/IPTV#72]
Can you Please add these android app Live Indian TV feed in your application ..

https://play.google.com/store/apps/details?id=com.straspo.Krik&hl=hi&gl=US
https://play.google.com/store/apps/details?id=com.jio.jioplay.tv&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.jio.media.ondemand&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=in.startv.hotstar.dplus&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.tv.v18.viola&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.sonyliv&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.graymatrix.did&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=tv.accedo.airtel.wynk&hl=en
https://play.google.com/store/apps/details?id=com.vodafone.vodafoneplay&hl=en_IN&gl=US

There are more than 600+ TV channels in India. Hypnotix have only those channels which are already available on YouTube.
Like USA have multiple feeds in your software, there is a need of multiple feed from India.

**Comment by freetv332** [comment]
These aren't feed, they're apps.. if you find out which feeds they use we can add them.
