### ISSUE TITLE
How to suggest channels?

### ISSUE THREAD

**Issue by Kaktoose** [Free-TV/IPTV#79]
I don't know how to suggest channels with pull requests. I can't seem to get it working. any other ways I can suggest them?

**Comment by nezbednik** [comment]
If you got the URLs, you can make a pull request by forking and then pull requesting changes from your fork. (when you change sum shed in your fork, there is automatically a PR button).
If you don't have URLs, then idk but you can probably write them down here :)

**Comment by Kaktoose** [comment]
I was thinking cbc Nova Scotia and and CTV Atlantic just to increase the spread of news channels available in Canada.

**Comment by nezbednik** [comment]
Huh, I don't live in Canada but I assume you do, but it looks like CTV Atlantic has a live stream on their website although it wants an account and asks you for your (TV?) provider. Maybe somebody can do it...?

**Comment by Kaktoose** [comment]
I might be able to find it for cbc Nova Scotia

**Comment by Sphinxroot** [comment]
#EXTINF:-1 tvg-logo="https://i.imgur.com/voWE9BE.png" group-title="News",CBC Halifax
https://cbclivedai3-i.akamaihd.net/hls/live/566977/event2/CBHT/master5.m3u8

**Comment by NezbednikSK** [comment]
that list literally does not include the aforementioned channels lmao

**Comment by Sphinxroot** [comment]
CBC Halifax = Nova Scotia and all CBC is what u get from offical source  at  https://gem.cbc.ca/ if there is any other link they will be  xtream-code and wont last long and  you can get dmca for those ..

CTV are  hard to get   mostly DMR  DASH MPD link that need to be converted to .m3u8 to be universal

**Comment by KAMI911** [comment]
Any update on this issue?

**Comment by KAMI911** [comment]
What is the next step here?

**Comment by KAMI911** [comment]
Closing the issue.
