### ISSUE TITLE
VH1 request

### ISSUE THREAD

**Issue by infid0** [Free-TV/IPTV#8]
Not is a issue, but a request. Sorry.
VH1 it's a free channel (67) of the italian DDT.
​
Name: VH1
Web Page: https://www.paramountnetwork.it/diretta-tv/1iwm9n/vh1
Streaming: https://content.uplynk.com/channel/36953f5b6546464590d2fcd954bc89cf.m3u8

The stream maybe is geoblocked, but for me in Italy, works fine on VLC. Thank you so much for this great project. :3

**Comment by lestercrowling** [comment]
Not geoblocked, works in Russia

**Comment by freetv332** [comment]
Cool, please make a pull request.

**Comment by infid0** [comment]
Wow! Thank you so much to everyone! @lestercrowling for testing the channel out of Italy and for creating the pull request for me. And @freetv332 for the huge work of this greatest project. Me and "Kodi" says thank you guys! :D

**Comment by Free-IPTV** [comment]
> 
> 
> Not geoblocked, works in Russia

Haha.... das kleine Arschloch Ghost meldet sich mal wieder. Ghost, verpiss dich, so Typen wie du, die versuchen, sich mit falscher Identität in geschlossene Repos zu kommen, BRAUCHEN WIR NICHT!!!
