### ISSUE TITLE
Question about forwarders

### ISSUE THREAD

**Issue by NezbednikSK** [Free-TV/IPTV#87]
So, I've made a thing.
If I were to add these channels using my forwarder, would it be allowed?
[sktv-forwarders.7m.pl](https://sktv-forwarders.7m.pl/)
You access the channels like [this](https://sktv-forwarders.7m.pl/TA3/)
I've done some channels, just wanna ask for approval / disapproval.

**Comment by freetv332** [comment]
Yes, as long as it works.
